scene: box
source_path: data/box_50.pickle
iterations: 20000
position_lr_init: 0.000179
position_lr_final: 0.00000179
position_lr_delay_mult: 0.01
position_lr_max_steps: 20000
feature_lr: 0.002
opacity_lr: 0.006
scaling_lr: 0.005
rotation_lr: 0.001
percent_dense: 0.008
lambda_dssim: 0.2
densification_interval: 800
opacity_reset_interval: 1200
densify_from_iter: 500
densify_until_iter: 8000
densify_grad_threshold: 0.000027
random_background: False
interval: 8